---
- name: Initialise folder devops
  hosts: 'all'
  become: yes

  vars_files:
    - devops.yaml

  pre_tasks:

    - name: checking limit arg
      fail:
          msg: "you must use -l or --limit - when you really want to use all hosts, use -l 'all'"
      when: ansible_limit is not defined
      run_once: true

    - name: "Create public directory devops"
      file:
        path: "{{ item.dest }}"
        #mode: "{{item.mode}}"
        state: directory
      with_items:
        - { dest: '{{ devops_dir }}', mode: '0777'}
        - { dest: '{{ devops_certs_dir }}', mode: '0707'}
        - { dest: '{{ devops_certs_public_dir }}', mode: '0707'}
        - { dest: '{{ devops_apps_dir }}', mode: '0707'}
  tasks:



