---
- name: "Initialise grafana app "
  hosts: 'all'
  become: yes

  vars_files:
    - devops.yaml
    - qcm.yaml
    - grafana.yaml

  pre_tasks:

    - name: checking limit arg
      fail:
          msg: "you must use -l or --limit - when you really want to use all hosts, use -l 'all'"
      when: ansible_limit is not defined
      run_once: true

  tasks:

    - name: "Create {{ docker_grafana_volume_data }} directory"
      file:
        path: "{{ item.dest }}"
        #mode: "{{item.mode}}"
        state: directory
      with_items:
        - { dest: '{{ docker_grafana_volume_data }}', mode: '0707'}

    - name: "Copying the {{ docker_grafana_volume_data }}/grafana.ini file"
      template:
          src="/root/playbook/centos7/templates/{{item}}.j2"
          dest="{{ docker_grafana_volume_data }}/{{item}}"
          mode=0644
      with_items:
        - grafana.ini

    - name: "Create {{ docker_qcm_network_name }} network"
      docker_network:
        name: "{{ docker_qcm_network_name }}"
        driver: bridge

    - name: "Stop running {{ docker_grafana_container_app_name }} container"
      docker_container:
        name: "{{ item }}"
        state: stopped
      ignore_errors: yes
      with_items:
        - "{{ docker_grafana_container_app_name }}"

    - name: "Remove {{ docker_grafana_container_app_name }} container"
      docker_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - "{{ docker_grafana_container_app_name }}"
      ignore_errors: yes

    - name:  "Create  container {{docker_grafana_container_app_img}} --> {{docker_grafana_container_app_name}} "
      docker_container:
        hostname: "{{ docker_grafana_container_app_name }}"
        name: "{{ docker_grafana_container_app_name }}"
        image: "{{ docker_grafana_container_app_img }}"
        # command: " --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles --web.external-url=/prometheus/ --web.route-prefix=/prometheus/"
        memory: 1024m
        state: started
        pull: true
        restart: yes
        restart_policy: unless-stopped
        networks:
          - name: "{{ docker_qcm_network_name }}"
        ports:
          - "{{ grafana_port }}:{{ grafana_port }}"
        volumes:
           - "{{ docker_grafana_volume_data }}/grafana.ini:/etc/grafana/grafana.ini"

    - name: "Get infos on {{ docker_grafana_container_app_name }} container"
      docker_container_info:
        name: "{{ docker_grafana_container_app_name }}"
      register: result

    - name: "Print information about {{ docker_grafana_container_app_name }} container"
      debug:
        var: result
      when: result
