---
- name: Install docker
  gather_facts: No
  hosts: 'all'

  vars:
    venv_home: "/devops/python"
    ansible_python_interpreter: "/usr/bin/python2"
  vars_files:
    - python.yaml
  pre_tasks:

      - name: checking limit arg
        fail:
            msg: "you must use -l or --limit - when you really want to use all hosts, use -l 'all'"
        when: ansible_limit is not defined
        run_once: true

      - name: "Supprimer {{ venv_home }}/{{ docker_venv }} répertoire et contenu"
        file:
          state: absent
          path: "{{ venv_home }}/{{ docker_venv }}/"

      - name: "Create public directory devops python"
        file:
          path: "{{ item.dest }}"
          state: directory
        with_items:
          - { dest: '/devops', mode: '0777'}
          - { dest: '{{ venv_home }}', mode: '0707'}

  tasks:


     - name: "Create virtualenv"
       shell: virtualenv "{{ venv_home }}/{{ docker_venv }}"
         creates="{{ venv_home }}/{{ docker_venv }}/bin/activate"

    #- name: "Create virtualenv"
    #  shell:
    #     virtualenv: "{{ venv_home }}/{{ docker_venv }} -p python2"
    #     creates: "{{ venv_home }}/{{ docker_venv }}/bin/activate"

    #- name: "create virtualenv"
    #  shell:
    #    virtualenv: "{{ venv_home }}/{{ docker_venv }}"
    #    virtualenv_python: python2

     #- name: "create virtualenv"
     # pip:
     #   virtualenv: "{{ venv_home }}/{{ docker_venv }}"
     #   virtualenv_python: python2


