---
- name: Install public keystore
  hosts: 'all'
  become: yes

  vars_files:
    - devops.yaml
    - certs.yaml

  pre_tasks:

    - name: checking limit arg
      fail:
          msg: "you must use -l or --limit - when you really want to use all hosts, use -l 'all'"
      when: ansible_limit is not defined
      run_once: true

    - name: "Create public directory devops"
      file:
        path: "{{ item.dest }}"
        #mode: "{{item.mode}}"
        state: directory
      with_items:
        - { dest: '{{ devops_dir }}', mode: '0777'}
        - { dest: '{{ devops_certs_dir }}', mode: '0707'}
        - { dest: '{{ devops_certs_public_dir }}', mode: '0707'}
  tasks:

    - name: "Create a keystore with letencrypt certificate/private key pair for {{centos7_server}}"
      community.general.java_keystore:
        name: "{{item}}"
        certificate_path: "/etc/letsencrypt/live/{{item}}/fullchain.pem"
        private_key_path: "/etc/letsencrypt/live/{{item}}/privkey.pem"
        password: "{{public_keystore_password}}"
        dest: "{{public_keystore}}"
      with_items:
       -  "{{centos7_server}}"

