---
- name: This sets up an cerbot
  hosts: 'all'

  pre_tasks:

    - name: checking limit arg
      fail:
        msg: "you must use -l or --limit - when you really want to use all hosts, use -l 'all'"
      when: ansible_limit is not defined
      run_once: true

    - name: Install yum certbot packages
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - epel-release
        - certbot
        - python2-certbot
        - python2-certbot-apache
        - mod_ssl

  tasks:
