---
- name: Clean nexus Docker
  hosts: 'all'
  become: yes

  vars_files:
    - certs.yaml
    - nexus.yaml

  tasks:
    - name: "Stop running nexus containers"
      docker_container:
        name: "{{ item }}"
        state: stopped
      ignore_errors: yes
      with_items:
        - "{{ docker_container_db_name }}"
        - "{{ docker_container_app_name }}"

    - name: "Remove nexus containers"
      docker_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - "{{ docker_container_db_name }}"
        - "{{ docker_container_app_name }}"

    - name: "Remove nexus network"
      docker_network:
        name: "{{ docker_network_name }}"
        state: absent

    - name: "Remove nexus volume"
      docker_volume:
        name: "{{ docker_volume_db_data }}"
        state: absent

