---
- name: Show passsword
  hosts: 'all'
  become: yes

  vars:

    docker_container_app_name: nexus-srv

  tasks:

  - name: Run a simple command (argv)
    community.docker.docker_container_exec:
      container: "{{ docker_container_app_name }}"
      command: /bin/bash -c "cat /nexus-data/admin.password"
      # command: /bin/bash -c "ls -lah"
      chdir: /root
    register: result

  - name: Print result
    debug:
      var: result.stdout


